Add support for dos partitions
Fixing the macro syntaxes in the previous commit leads to this
error:
  part.c:270:3: error: #error neither CONFIG_MAC_PARTITION
  nor CONFIG_DOS_PARTITION nor CONFIG_ISO_PARTITTION configured!

Configuration files using CONFIG_MMC to have been update to
define CONFIG_DOS_PARTITION.

This patch also imports corresponding implementation from u-boot
version 1.1.4 to fix this error.

Portion of file that add dependency on sprintf() - but is
really not useful in context of x-loader have been removed
by wrapping it under #ifdef NOT_REQUIRED_IN_X_LOAD...#endif.